Stack two arrays vertically and horizontally.

In [10]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.stack((a,b), axis=0)
d = np.stack((a,b), axis=1)
print("Vertically Stacked Array:\n", c)
print(print("Horizontally Stacked Array:\n", d))


Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]]
Horizontally Stacked Array:
 [[1 4]
 [2 5]
 [3 6]]
None
