Sort a 2D array row-wise.

In [5]:
import numpy as np 

arr_2D_unsorted = np.array([[5,2,7],[9,5,1]])
print("Sorted 2D array by row:\n" , np.sort(arr_2D_unsorted , axis= 1))

Sorted 2D array by row:
 [[2 5 7]
 [1 5 9]]


Sort a 2D array column-wise.

In [8]:
import numpy as np 

arr_2D_unsorted = np.array([[9,8,7],[4,9,3]])
print("Sorted 2D array by Column:\n" , np.sort(arr_2D_unsorted , axis= 0))

Sorted 2D array by Column:
 [[4 8 3]
 [9 9 7]]


Sort a N-D array both row-wise and column-wise.

In [9]:
import numpy as np

# Original unsorted 2D array
arr = np.array([[9, 2, 7],
                [6, 5, 1],
                [3, 8, 4]])

# Step 1: Row-wise sort (sort each row)
row_sorted = np.sort(arr, axis=1)

# Step 2: Column-wise sort (sort each column of the row-sorted array)
fully_sorted = np.sort(row_sorted, axis=0)

print("Original array:\n", arr)
print("\nRow-wise sorted:\n", row_sorted)
print("\nRow-wise then Column-wise sorted:\n", fully_sorted)


Original array:
 [[9 2 7]
 [6 5 1]
 [3 8 4]]

Row-wise sorted:
 [[2 7 9]
 [1 5 6]
 [3 4 8]]

Row-wise then Column-wise sorted:
 [[1 4 6]
 [2 5 8]
 [3 7 9]]
