Split a 1D array of size 12 into 3 equal parts.

In [8]:
import numpy as np

arr_1D = np.arange(12)
split_arrays = np.split(arr_1D, 3)

for part in split_arrays:
    print(part)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
