Create a 3x3 array and extract the second column.

In [ ]:
import numpy as np

arr = np.random.rand(3,3)
# print(arr)
print("Second Column \n" ,arr[:,1])

[[0.7553141  0.59188219 0.59832876]
 [0.65633954 0.39082127 0.65624547]
 [0.81124306 0.10686732 0.84716424]]
Second Column 
 [0.59188219 0.39082127 0.10686732]
