Find the inverse of a 3x3 matrix.

In [15]:
import numpy as np

matrix = np.random.rand(3,3)
inverse_matrix = np.linalg.inv(matrix)

print("Orginal Matrix\n")
print(matrix)
print("\nInverse Matrix\n")
print(inverse_matrix)

Orginal Matrix

[[0.31637846 0.22237307 0.49437346]
 [0.30711198 0.57079148 0.73948382]
 [0.79625709 0.37049299 0.47726292]]

Inverse Matrix

[[ 0.02204268 -1.091274    1.6680159 ]
 [-6.26512204  3.43756263  1.16348476]
 [ 4.82675705 -0.84787271 -1.59080542]]
