Perform union, intersection, and difference on two arrays.

In [16]:
import numpy as np

# array 1 
arr_1 = np.array([[1,2,3],
                 [4,3,5]])

# array 2
arr_2 = np.array([[3,7,2],
                 [6,2,1]])

flat_1 = arr_1.flatten()
flat_2 = arr_2.flatten()

print("array one\n")
print(flat_1)
print("\narray two\n")
print(flat_2)
# union

union_arr = np.union1d(flat_1,flat_2)
print("\nUnion\n")
print(union_arr)

# intersection

intersection_arr = np.intersect1d(flat_1,flat_2)
print("\nIntersection\n")
print(intersection_arr)

# difference

difference_arr = np.setdiff1d(flat_1,flat_2)
print("\nDifference\n")
print(difference_arr)

array one

[1 2 3 4 3 5]

array two

[3 7 2 6 2 1]

Union

[1 2 3 4 5 6 7]

Intersection

[1 2 3]

Difference

[4 5]
