Create an array of floats and convert it to integers

In [14]:
import numpy as np

float_arr = np.random.rand(3,3) 
int_arr = float_arr.astype(int)
print(int_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Create a 4×4 array with random floats between 5 and 10, and convert all values to integers.

In [21]:
rand_floats = np.random.rand(4, 4)
scaled_floats = rand_floats * 5 + 5
int_array = scaled_floats.astype(int)
print(int_array)


[[9 6 6 9]
 [9 9 6 8]
 [7 8 9 5]
 [8 6 7 7]]


Create a 1D array of 6 random float values between 0 and 1, then round each value to 2 decimal places.

In [26]:
arr_1D = np.random.rand(2, 2)
rounded_arr = np.round(arr_1D, 2)
print(rounded_arr)

[[0.43 0.48]
 [0.4  0.68]]
