Create a 5x5 array with 1s on the border and 0 inside.

In [7]:
import numpy as np

arr = np.ones((5,5))
arr[1:4 , 1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Create a 6×6 array filled with 0s, and set a 4×4 block in the center to 1s.



In [11]:
arr_1 = np.zeros((6,6))
arr_1[1:5 , 1:5] = 1
print(arr_1)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
