Find the sum of the main diagonal of a 4x4 matrix.

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
print(arr)
matrix_digonal =arr.diagonal()
sum_of_digonal = matrix_digonal.sum()
print(f"the sum of matrix digonal: {matrix_digonal} = {sum_of_digonal}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
the sum of matrix digonal:[ 1  6 11 16] = 34
